apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - bencher
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: springboot
          image: BASE_DOCKER_REPO/kubench-springboot:latest
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
---
kind: Service
apiVersion: v1
metadata:
  name: springboot
spec:
  type: ClusterIP
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
