apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-induzo-deployment
spec:
  selector:
    matchLabels:
      app: go-induzo
  replicas: 3
  template:
    metadata:
      labels:
        app: go-induzo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - bencher
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: go-induzo
          image: BASE_DOCKER_REPO/kubench-go-induzo:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "1000m"
---
kind: Service
apiVersion: v1
metadata:
  name: go-induzo
spec:
  type: ClusterIP
  selector:
    app: go-induzo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
